music/urls.py
from django.conf.urls import url
from django.contrib.auth import views as av
from django.urls import reverse_lazy

from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^favorite_albums/$', views.fav_albums, name='favorite_albums'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', av.LoginView.as_view(template_name='music/login.html'), name='login'),
    url(r'^logout/$', av.LogoutView.as_view(template_name='music/logout.html'), name='logout'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<current_template>[a-zA_Z]+)/(?P<song_id>[0-9]+)/$', views.delete_song,
        name='delete_song'),
    url(r'^(?P<album_id>[0-9]+)/update/$', views.album_update_view, name='album-update'),
    url(r'^(?P<album_id>[0-9]+)/(?P<current_template>[a-zA_Z]+)/favorite_album/$', views.favorite_album,
        name='favorite_album'),
    url(r'^(?P<song_id>[0-9]+)/(?P<current_template>[a-zA_Z]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^password-reset/$',
        av.PasswordResetView.as_view(email_template_name='music/password_reset_email.html',
                                     success_url=reverse_lazy('music:password_reset_done'),
                                     template_name='music/password_reset.html'), name='password_reset'),
    url(r'^password-reset/done/$',
        av.PasswordResetDoneView.as_view(template_name='music/password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$',
        av.PasswordResetConfirmView.as_view(success_url=reverse_lazy('music:password_reset_complete'),
                                            template_name='music/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        av.PasswordResetCompleteView.as_view(template_name='music/password_reset_complete.html'),
        name='password_reset_complete'),
]

my_first_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from .process_color import *

from django.contrib.auth.models import Permission, User

WEBSITE_NAMES = [
    'bandcamp',
    'soundcloud',
    'spotify',
    'itunes',
    'facebook',
    'vk',
]


class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.SET_NULL, null=True)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    website_1 = models.CharField(max_length=100, blank=True)
    website_2 = models.CharField(max_length=100, blank=True)
    website_3 = models.CharField(max_length=100, blank=True)
    website_4 = models.CharField(max_length=100, blank=True)
    website_5 = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    color = models.CharField(max_length=10)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.webInstances = []
        self.webSites = set()
        if self.album_logo:
            self.define_color()
        if len(self.webInstances) == 0:
            self.set_websites()

    def __str__(self):
        return '{} - {}'.format(self.artist, self.album_title)

    def define_color(self):
        self.color = get_color(self.album_logo.path)

    def set_websites(self):
        inputs = [self.website_1, self.website_2, self.website_3, self.website_4, self.website_5]
        for inp in inputs:
            if inp:
                lnk = inp[inp.find('.') + 1:inp.find('.com')]
                if lnk == '':
                    lnk = inp[inp.find('://') + 3:inp.find('.com')]
                weblink = WebLink(url=inp, website=lnk)
                if lnk in WEBSITE_NAMES:
                    if weblink.website not in self.webSites:
                        self.webInstances.insert(0, weblink)
                        self.webSites.add(weblink.website)
                else:
                    weblink.website = 'link'
                    if weblink.website not in self.webSites:
                        self.webInstances.append(weblink)
                        self.webSites.add(weblink.website)


def add_demo_albums(user):
    prim_k = (107, 108, 109)
    for pk in prim_k:
        album_to_copy = Album.objects.get(pk=pk)
        album_to_copy.pk = None
        album_to_copy.save()
        album_to_fill = Album.objects.last()
        album_to_fill.user = user
        album_to_fill.save()
        songs_to_copy = Song.objects.filter(album=Album.objects.get(pk=pk))
        for song in songs_to_copy:
            song.pk = None
            song.save()
            s2 = Song.objects.last()
            s2.album = album_to_fill
            s2.save()


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True)
    audio_file = models.FileField(default='')
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


class WebLink(models.Model):
    url = models.CharField(max_length=100)
    website = models.CharField(max_length=100)

    def __init__(self, url, website, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self.url = url
        self.website = website

music/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Album, Song


class UserRegForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1',  'password2']


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['artist',
                  'album_title',
                  'genre',
                  'website_1',
                  'website_2',
                  'website_3',
                  'website_4',
                  'website_5',
                  'description',
                  'album_logo']


class SongForm(forms.Form):
    model = Song
    audio_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Album, Song, User, add_demo_albums
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AlbumForm, SongForm, UserRegForm
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from os import remove
import eyed3

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def index(request):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        albums = Album.objects.filter(user=request.user)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query) &
                Q(album__user=request.user)
            ).distinct()
            return render(request, 'music/index.html', {
                'albums': albums,
                'songs': song_results,
                'q': query,
            })
        else:
            return render(request, 'music/index.html', {'albums': albums, 'favs': 'all'})


def fav_albums(request):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        albums = Album.objects.filter(user=request.user, is_favorite=True)
        return render(request, 'music/index.html', {'albums': albums, 'favs': 'favs'})


def create_album(request):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/album_form.html', context)
            album.save()
            return render(request, 'music/detail.html', {'album': album})
        context = {
            "form": form,
        }
    return render(request, 'music/album_form.html', context)


def create_song(request, album_id):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if form.is_valid():
            for obj in request.FILES.getlist('audio_files'):
                albums_songs = album.song_set.all()
                song = Song()
                song.album = album
                song.audio_file = obj
                # grabbing song title from ID3 tags
                song.song_title = eyed3.load(obj.temporary_file_path()).tag.title
                for s in albums_songs:
                    if s.song_title == song.song_title:
                        context = {
                            'album': album,
                            'form': form,
                            'error_message': 'You already added that song - {}'.format(song.song_title),
                        }
                        return render(request, 'music/create_song.html', context)
                file_type = song.audio_file.url.split('.')[-1]
                file_type = file_type.lower()
                if file_type not in AUDIO_FILE_TYPES:
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'Audio file must be WAV, MP3, or OGG',
                    }
                    return render(request, 'music/create_song.html', context)

                song.save()
            return render(request, 'music/detail.html', {'album': album})
        context = {
            'album': album,
            'form': form,
        }
        return render(request, 'music/create_song.html', context)


def detail(request, album_id):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album, 'user': user})


def delete_album(request, album_id):
    if not request.user.is_authenticated:
        return redirect('music:index')
    else:
        album = Album.objects.get(pk=album_id)
        albums_songs = album.song_set.all()
        for song in albums_songs:
            remove(song.audio_file.path)
        remove(album.album_logo.path)
        album.delete()
        return redirect('music:index')


def delete_song(request, album_id, song_id, current_template):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        album = get_object_or_404(Album, pk=album_id)
        song = Song.objects.get(pk=song_id)
        remove(song.audio_file.path)
        song.delete()
        if current_template == 'songs':
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            return render(request, 'music/songs.html', {'song_list': users_songs})
        else:
            return render(request, 'music/detail.html', {'album': album})


def favorite(request, song_id, current_template):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        song = get_object_or_404(Song, pk=song_id)
        album = song.album
        try:
            if song.is_favorite:
                song.is_favorite = False
            else:
                song.is_favorite = True
            song.save()
        except (KeyError, Song.DoesNotExist):
            return JsonResponse({'success': False})
        else:
            if current_template == 'songs':
                song_ids = []
                for album in Album.objects.filter(user=request.user):
                    for song in album.song_set.all():
                        song_ids.append(song.pk)
                users_songs = Song.objects.filter(pk__in=song_ids)
                return render(request, 'music/songs.html', {'song_list': users_songs})
            else:
                return render(request, 'music/detail.html', {'album': album})


def favorite_album(request, album_id, current_template):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        album = get_object_or_404(Album, pk=album_id)
        try:
            if album.is_favorite:
                album.is_favorite = False
            else:
                album.is_favorite = True
            album.save()
        except (KeyError, Album.DoesNotExist):
            return JsonResponse({'success': False})
        else:
            if current_template == 'index':
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
            else:
                return render(request, 'music/detail.html', {'album': album})


def register(request):
    if request.method == 'POST':
        form = UserRegForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Welcome, {}'.format(username))
            add_demo_albums(User.objects.get(username=username))
            return redirect('music:login')
    else:
        form = UserRegForm()
    return render(request, 'music/register.html', {'form': form})


def songs(request, filter_by):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })


def album_update_view(request, album_id):
    if not request.user.is_authenticated:
        return redirect('music:register')
    else:
        obj = get_object_or_404(Album, pk=album_id)
        form = AlbumForm(request.POST or None, request.FILES or None, instance=obj)
        context = {'form': form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.set_websites()
            obj.save()
            messages.success(request, "Album info updated")
            return render(request, 'music/detail.html', {'album': obj})
        return render(request, 'music/album_update.html', context)

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block content %}

    <div class="container-fluid songs-container px-0 px-md-3">

        <div class="row">

            <div class="col-12 col-md-6 col-lg-5 col-xl-4">

                <!-- ******* ALBUM CARD FROM TEMPLATE ******* -->

                {% include 'music/album_card.html' %}

            </div>

            <div class="col-12 col-md-6">

                <!-- ******* SONGS CARD NAV ******* -->

                <div class="row mx-1 text-center">
                    <a href="{% url 'music:detail' album.id %}"
                       class="btn btn-dark active col-6"
                       role="button"
                       aria-pressed="true">View All</a>
                    <a href="{% url 'music:create_song' album.id %}"
                       class="btn btn-dark col-6 card-{{ album.color }}"
                       role="button">Add New Song</a>
                </div>

                <!-- ******* SONGS CARD ******* -->

                <div class='card card-{{ album.color }} bg-dark text-white mw-20 mx-1'>
                    <div class="card-body px-0 pb-0">
                        <h2 class="mb-4 d-none d-md-block pl-md-4">Songs</h2>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <!-- ******* PLAYER START ******* -->

                        {% for song in album.song_set.all %}
                            <div class="container">
                                <div class="row px-0 audioPlayer">

                                    <!-- ******* INFO (title, progress bar and timing) ******* -->

                                    <div class="my-0 p-0 col-10 border-top">
                                        <div class="container">
                                            <div class="playerContainer">
                                                <div class="info">

                                                    <div class="row justify-content-between text-{{ album.color }}">
                                                        <span class="audioName col-9">{{ song.song_title }}</span>
                                                        <div class="timing col-3">
                                                            <span id="start-{{ song.id }}">0:00</span>
                                                        </div>
                                                    </div>

                                                    <div class="seekBar">
                                                    <span class="outer outer-{{ song.id }}">
                                                        <span class="progress progress-{{ album.color }} inner"
                                                              id="progress-{{ song.id }}"></span>
                                                    </span>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>

                                    </div>


                                    <div class="m-0 p-0 border-top row justify-content-between col-2 text-center">

                                        <!-- ******* AUDIO FILE ******* -->

                                        <audio class="audio d-none" id="audio-{{ song.id }}">
                                            <source src="{{ song.audio_file.url }}">
                                        </audio>

                                        <!-- ******* PLAY-PAUSE BUTTON ******* -->

                                        <button
                                                class="btn btn-outline-{{ album.color }} bo-plr col-6 col-md-4 my-0 px-0"
                                                onclick="playSong('{{ song.id }}');"
                                                id="pbtn-{{ song.id }}">
                                            <div id="{{ song.id }}">
                                                <div class="playbutton play">
                                                    <i class="fas fa-play"></i>
                                                    <i class="fas fa-pause"></i>
                                                </div>
                                            </div>
                                        </button>

                                        <!-- ******* FOR BIG SCREENS ******* -->

                                        <div class="d-none d-md-flex m-0 p-0 col-8">
                                            <a href="{% url 'music:favorite' song.id 'detail' %}"
                                               class="btn btn-outline-{{ album.color }} py-2 col-6">
                                                <i class="fab fa-gripfire {% if song.is_favorite %}active{% endif %}"></i>
                                            </a>

                                            <!-- ******* DELETE BUTTON ******* -->

                                            <form action="{% url 'music:delete_song' song.album.id 'detail' song.id %}"
                                                  method="post" class="btn btn-outline-{{ album.color }} my-0 col-6">
                                                {% csrf_token %}
                                                <input type="hidden" name="album_id" value="{{ album.id }}">
                                                <button class="btn btn-link" type="submit">
                                                    <i class="fas fa-trash-alt"></i>
                                                </button>
                                            </form>
                                        </div>

                                        <!-- ******* FOR SMALL SCREENS ******* -->

                                        <div class="d-flex d-md-none m-0 p-0 col-6 dropleft">

                                            <!-- ******* DROPDOWN TOGGLE ******* -->

                                            <a href="#"
                                               class="btn btn-lg btn-outline-{{ album.color }} bo-plr col-12 my-0 px-0 dropdown-toggle"
                                               role="button" id="dropdownMenuLink" data-toggle="dropdown"
                                               aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-h"></i>
                                            </a>

                                            <div class="dropdown-menu py-0" aria-labelledby="dropdownMenuLink">

                                                <!-- ******* FAV BUTTON ******* -->

                                                <a href="{% url 'music:favorite' song.id 'detail' %}"
                                                   class="btn btn-outline-{{ album.color }} py-2">
                                                    <i class="fab fa-gripfire {% if song.is_favorite %}active{% endif %}"></i>
                                                </a>

                                                <!-- ******* DELETE BUTTON ******* -->

                                                <form action="{% url 'music:delete_song' song.album.id 'detail' song.id %}"
                                                      method="post" class="btn btn-outline-{{ album.color }} my-0">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="album_id" value="{{ album.id }}">
                                                    <button class="btn btn-link" type="submit">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </form>

                                            </div>
                                        </div>


                                    </div>
                                </div>
                            </div>

                        {% endfor %}

                        <!-- ******* PLAYER END ******* -->

                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}{% if q %}Search Results{% else %}{{user}}'s Albums{% endif %}{% endblock %}
{% block albums_active %}active{% endblock %}
{% block content %}
    <div class="content-cust">

        <div class="albums-container container-fluid px-0 px-md-3">

            {% if albums or songs %}

                {% if albums %}

                    <div class="row justify-content-between">

                        {% for album in albums %}

                            <!-- ******* ALBUM CARD START ******* -->

                            <div class="col-12 col-md-6 col-lg-4 my-3">
                                <div class='card card-{{ album.color }} alb-card bg-dark text-white mx-auto'
                                     style="min-width: 20em; max-width: 30em">

                                    <!-- ******* TITLE AND LOGO ******* -->

                                    <div class="card-header  text-center">
                                        <h3>{{ album.album_title }}</h3>
                                        <h5>{{ album.artist }}</h5>
                                    </div>

                                    <a href="{% url 'music:detail' album.id %}">
                                        <img src="{{ album.album_logo.url }}" alt="{{ album.album_logo.url }}"
                                             class="card-img-top"
                                             width="400">
                                    </a>

                                    <!-- ******* BUTTONS ******* -->

                                    <div class="card-body">
                                        <div class="row justify-content-between mx-1">
                                            <div class="btn-group" role="group">

                                                <a href="{% url 'music:detail' album.id %}"
                                                   class="btn btn-outline-{{ album.color }} btn-sm pt-1">View
                                                    Details</a>


                                                <a href="{% url 'music:album-update' album.id %}"
                                                   class="btn btn-outline-{{ album.color }} btn-sm pt-1"
                                                   data-toggle="tooltip" data-placement="top" title="Edit"><i
                                                        class="fas fa-pen"></i></a>


                                                <form class="btn btn-outline-{{ album.color }} btn-sm {{ album.color }} "
                                                      action="{% url 'music:delete_album' album.id %}"
                                                      method="post" style="display: inline"
                                                      data-toggle="tooltip" data-placement="top" title="Delete">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="album_id" value="{{ album.id }}">
                                                    <button class="btn btn-link" type="submit">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </form>

                                            </div>

                                            <a href="{% url 'music:favorite_album' album.id 'index' %}"
                                               data-toggle="tooltip" data-placement="top" title="Favorite">
                                                <i class="fab fa-gripfire fa-gripfire-x fa-2x {% if album.is_favorite %}active{% endif %}"></i>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>

                {% endif %}

                <!-- ******* WHEN SEARCHING AND THERES SONGS ******* -->

                {% if songs %}

                    <div class='card card-white bg-dark text-white mw-20 my-5 col-12'>
                        <div class="card-body px-0 pb-0">

                            <h2 class="mb-2 text-center text-md-left pl-md-4">Songs</h2>

                            {% if error_message %}
                                <p><strong>{{ error_message }}</strong></p>
                            {% endif %}

                            {% for song in songs %}

                                <!-- ******* PLAYER FROM TEMPLATE******* -->

                                {% include 'music/player_template.html' %}

                            {% endfor %}
                        </div>
                    </div>
                {% endif %}


            {% elif q %}

                <h1>No results for {{ q }}</h1>

            {% else %}

                <!-- ******* IF NO CONTENT ******* -->

                <div class="col-12 col-md-6">

                    <div class="card p-3">

                        <div class="text-center mb-3 ">
                            <h2>You have no {% if favs == 'favs' %}favorite {% endif %}albums in library</h2>
                        </div>

                        {% if favs == 'all' %}
                            <div class="text-center">
                                <a class="btn btn-outline-info" role="button" href="{% url 'music:create_album' %}">Add
                                    Album</a>
                            </div>

                        {% else %}
                            <div class="text-center">
                                <a class="btn btn-outline-info" role="button" href="{% url 'music:index' %}">Back to
                                    your albums</a>
                            </div>
                        {% endif %}
                    </div>

                </div>

            {% endif %}
        </div>
    </div>
{% endblock %}